name: dalil_hama
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  dartz: ^0.10.1
  logger: ^2.5.0
  go_router: ^17.0.0
  get_it: ^9.1.1
  injectable: ^2.5.0
  retrofit: ^4.9.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  url_launcher: ^6.3.1
  hive_flutter: ^1.1.0
  hydrated_bloc: ^10.0.0
  photo_view: ^0.15.0
  conditional_builder_null_safety: ^0.0.6
  google_maps_flutter: ^2.13.1
  platform_identity:
    git: https://github.com/SalemZakkar/platform_identity.git
  core_package:
    path: core_package
  graphql_flutter: ^5.2.1

dependency_overrides:
  analyzer: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.3
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  flutter_gen: ^5.10.0
  injectable_generator: ^2.11.0
  flutter_gen_runner: ^5.10.0
#  retrofit_generator: ^10.0.2
#  flutter_gen: ^5.12.0
  retrofit_generator: ^10.2.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600


flutter_gen:
  output: lib/generated/generated_assets/
  integrations:
    flutter_svg: true
